// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Ir3sK-qTL5oeRg9Wfw75-jQZCUIxqN4',
    appId: '1:407012033822:web:4f77db2bdcb1360a50b50f',
    messagingSenderId: '407012033822',
    projectId: 'app2-c2f72',
    authDomain: 'app2-c2f72.firebaseapp.com',
    storageBucket: 'app2-c2f72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVPjoZyh_MDllDxJ6RLtDxklpeMOxDddU',
    appId: '1:407012033822:android:f1abd7c8559b73cc50b50f',
    messagingSenderId: '407012033822',
    projectId: 'app2-c2f72',
    storageBucket: 'app2-c2f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByG7LQ-RzOsepoQd5sIXGyvz7gB9HpPFU',
    appId: '1:407012033822:ios:24d3b62b215d9a0750b50f',
    messagingSenderId: '407012033822',
    projectId: 'app2-c2f72',
    storageBucket: 'app2-c2f72.appspot.com',
    iosClientId: '407012033822-qm0afn8fotbte503s6h9ihofge1bf0a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByG7LQ-RzOsepoQd5sIXGyvz7gB9HpPFU',
    appId: '1:407012033822:ios:24d3b62b215d9a0750b50f',
    messagingSenderId: '407012033822',
    projectId: 'app2-c2f72',
    storageBucket: 'app2-c2f72.appspot.com',
    iosClientId: '407012033822-qm0afn8fotbte503s6h9ihofge1bf0a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );
}
